### ISSUE TITLE
Add proper responsive breakpoints

### ISSUE THREAD

**Issue by ccsCoder** [ccsCoder/ng-weather#4]
Right now, the app only has one breakpoint that is set at `max-width: 500px`. This is neither ideal nor does it target a decent number of devices.

Add common breakpoints for responsiveness and make relevant css changes.

**Comment by ravenblack24** [comment]
I'd like to have a go at this one please!

**Comment by ccsCoder** [comment]
@ravenblack24 all yours. Go ahead

**Comment by ravenblack24** [comment]
Pull request submitted #7
